modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="${license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://mealam1.github.io/BlueLib/"
logoFile="bluelib.png"
credits="Anyone who contributed to the Source Code of BlueLib!"
authors="${mod_author}"
description='''${description}'''

[[dependencies.bluelib]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.bluelib]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"