# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Common
modId=bluelib
modDisplayName=BlueLib
modLicense=MIT License
group=software.bluelib
modAuthors=Dan, Aram
modDescription=BlueLib is an All round Minecraft mod library that offers data-driven features, allowing users to implement and customize its features with full freedom. \nIt supports both Resource and Datapacks, ensuring seamless integration and flexibility.